server:
    port: 8082

jwt:
    secret: "test_key"

spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: api-gateway
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
                        allowedHeaders: "*"
        kubernetes:
            reload:
                enabled: false
                url-expression: "uri+'/'"
            discovery:
                enabled: false
                locator:
                    enabled: false
                    url-expression: "http://'+serviceId+':'+getPort()"
                    lower-case-service-id: true
